version: '2'
services:
  nginx:
    image: "tacsi/nginx-arm-bpi"
    build: ./nginx/
    links:
      - "transmission:transmission.local"
      - "expense-reporter:expense-reporter.local"
      - "sms-parser:sms-parser.local"
    ports:
      - "80:80"
      - "443:443"
    restart: always

  transmission:
    image: "tacsi/transmission-arm-bpi"
    build: ./transmission/
    volumes:
      - /home/bpi/.config/transmission/:/app
      - /media/cuccok/torrents/:/app/torrents
    environment:
      - TRANSMISSION_USER=bpi
      - TRANSMISSION_PASSWORD=tonb314
    ports:
      - "51413:51413/tcp"
      - "51413:51413/udp"
      - "9091:9091"

  expense-reporter:
    image: "tacsi/expense-reporter-arm-bpi"
    build: ./expense-reporter/
    volumes:
      - /home/bpi/client_secret.json:/app/client_secret.json:ro
    restart: always

  sms-parser:
    image: "tacsi/sms-parser-arm-bpi"
    build: ./sms-parser/
    links:
      - "mongodb:mongodb"
    restart: always

  mongodb:
    image: "ivanmarban/armhf-mongodb"
    volumes:
      - /home/bpi/mongo-data:/var/lib/mongodb
    restart: always

