version: '2'
services:
  nginx:
    image: "tacsi/nginx-arm-bpi"
    build: ./nginx/
    links:
      #- "transmission:transmission.local"
      - "expense-reporter:expense-reporter.local"
      - "sms-parser:sms-parser.local"
    ports:
      - "80:80"
      - "443:443"
    restart: always

  expense-reporter:
    image: "tacsi/expense-reporter-arm-bpi"
    build: ./expense-reporter/
    volumes:
      - /home/bpi/client_secret.json:/app/client_secret.json:ro
    restart: always

  sms-parser:
    image: "tacsi/sms-parser-arm-bpi"
    build: ./sms-parser/
    links:
      - "mongodb:mongodb"
    restart: always

  mongodb:
    image: "ivanmarban/armhf-mongodb"
    volumes:
      - /home/bpi/mongo-data:/var/lib/mongodb
    restart: always

  torrent:
    image: "lsioarmhf/deluge"
#    ports:
#      - "8000:80"
#      - "5000:5000"
#      - "51413:51413"
#      - "6881:6881/udp"
    volumes:
      - /home/bpi/torrent-config:/config
      - /media/cuccok/torrents:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    network_mode: "host"
    restart: always
